### PR TITLE
UI split

### PR DESCRIPTION
**Pull request by tomusdrw**

### CODE REVIEW

**Comment by goldylucks** [comment]
this is too big to review without explanations
so merge if u think it's ok :)

**Comment by tomusdrw** [comment]
It's not that big. I've just:
1. removed `status/rpc-docs` since it seems they were not used anywhere
2. Removed `src/web` from `.gitignore` files
3. Committed compiled JS files.

**Comment by tomusdrw** [comment]
I can walk you through the changes. Although I think it will need another merge when #27 gets in.

**Comment by goldylucks** [comment]
merge at will

**Pull request merged**
